name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main, dev]

jobs:

  heavy-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/playwright.yml
    with:
      commit_sha: ${{ github.event.workflow_run.head_sha }}
  migrate:
    needs: heavy-tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/db-migrate.yml
    with:
      branch_name: ${{ github.event.workflow_run.head_branch }}
    secrets: inherit

  release:
    needs: migrate
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: false
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Map all remote branches locally for Semantic Release
        run: |
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            git branch --track "$branch" "origin/$branch" 2>/dev/null || true
          done
          git checkout -B ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/actions/setup-project

      - name: Semantic Release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_REF: refs/heads/${{ github.event.workflow_run.head_branch }}
