name: CI

on:
  push:
    branches: [main, next, next-major, beta, alpha]
  pull_request:
    branches: [main, next, next-major, beta, alpha]

jobs:
  lint-types:
    uses: ./.github/workflows/check-lint-types.yml
    
  unit-tests:
    uses: ./.github/workflows/test-unit.yml

  storybook-tests:
    if: >
      (github.event_name == 'pull_request' && github.base_ref == 'main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/test-storybook.yml

  e2e-tests:
    if: >
      (github.event_name == 'pull_request' && github.base_ref == 'main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/playwright.yml