name: DB Migrations
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          node-version: 'lts/*'

      - name: Set Environment
        id: db-env
        shell: bash
        run: |
          if [[ "${{ inputs.branch_name }}" == "production" ]]; then
            LOCAL_DB_URL="${{ secrets.DATABASE_URL_PROD }}"
          else
            LOCAL_DB_URL="${{ secrets.DATABASE_URL_PREVIEW }}"
          fi

          # Сначала маскируем переменную для вывода логов текущего шага
          echo "::add-mask::$LOCAL_DB_URL"

          # Затем сохраняем её в глобальное окружение для следующих шагов
          echo "DATABASE_URL=$LOCAL_DB_URL" >> $GITHUB_ENV

      - name: Run Drizzle Migrations
        run: bunx drizzle-kit migrate
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
