name: DB Migrations
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          node-version: 'lts/*'

      - name: Set Environment
        id: db-env
        shell: bash
        run: |
          if [[ "${{ inputs.branch_name }}" == "production" ]]; then
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PREVIEW }}" >> $GITHUB_ENV
          fi
          echo "::add-mask::$DATABASE_URL"

      - name: Run Drizzle Migrations
        run: bunx drizzle-kit migrate
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
