name: Storybook Tests
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project

      - name: Run Storybook Tests
        run: bun run storybook:test
